# MerMer Default Config

title = "TideBitBridge"

[base]
folder = "TideBitBridge"
static = "./build/frontend/"
debug = false

[blockchain]
type = "ethereum"

[database]
type = "firebase"

[extension]
CHROME_ID = "nkbihfbeogaeaoehlefnkodbefgpgknn",
FIREFOX_ID = "webextension@metamask.io"


[api]
pathname = [
  "get | /,/version | Static.Utils.readPackageInfo"
]